export const CHANGE_USER_LOGGED_IN_STATUS = 'CHANGE_USER_LOGGED_IN_STATUS';

export const CHANGE_CREATE_BOARD_FORM_STATUS =
  'CHANGE_CREATE_BOARD_FORM_STATUS';
export const CHANGE_CREATE_BOARD_BACKGROUND = 'CHANGE_CREATE_BOARD_BACKGROUND';
